apiVersion: v2
name: aws-argocd-appofapps
description: Root App of Apps chart — bootstraps all ArgoCD applications
type: application
version: 0.2.0

dependencies:
  - name: argocd-apps
    version: "2.0.4"
    repository: https://argoproj.github.io/argo-helm